In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("PhonePe_Transaction_Statement.csv" , skiprows =2  ,on_bad_lines = 'skip')

In [3]:
data

,Date,Time,Transaction Details,Transaction ID,UTR,Transaction Type,Credit/debit instrument,Amount
0,2025-01-01,\t00:26,Paid to Siddharth Singh,T2501010026524220783677,2.822167e+11,Debit,XXXXXXXXXXXXX6304,500.0
1,2025-01-01,\t13:56,Paid to Sandeep Kumar,T2501011356097139939145,4.141582e+11,Debit,XXXXXXXXXXXXX6304,500.0
2,2025-01-01,\t14:32,Paid to CAFE CULTURE,T2501011432219419492858,7.206843e+11,Debit,XXXXXXXXXXXXX6304,15.0
3,2025-01-01,\t16:34,Paid to Amit Kumar Srivastava,T2501011634408860803177,7.446455e+11,Debit,XXXXXXXXXXXXX6304,50.0
4,2025-01-01,\t16:37,Paid to Amit Kumar Srivastava,T2501011637217265742068,1.386754e+11,Debit,XXXXXXXXXXXXX6304,120.0
...,...,...,...,...,...,...,...,...
1636,2026-01-29,\t21:43,Paid to Kanak Sweets,T2601292143388713672293,5.158323e+11,Debit,XXXXXXXXXXXXX6304,30.0
1637,This is an automatically generated statement. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1638,Visit https://www.phonepe.com/terms-conditions...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1639,Do not fall prey to fictitious offers of winni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1640,The contents of this email and document are co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data = data.copy()

In [5]:
data["Transaction Details"] = data["Transaction Details"].astype(str).str.replace(r"Paid to" , "",regex = True )

In [6]:
data = data.drop(["Transaction ID" , "UTR" , "Credit/debit instrument"] , axis =1)

In [7]:
data

,Date,Time,Transaction Details,Transaction Type,Amount
0,2025-01-01,\t00:26,Siddharth Singh,Debit,500.0
1,2025-01-01,\t13:56,Sandeep Kumar,Debit,500.0
2,2025-01-01,\t14:32,CAFE CULTURE,Debit,15.0
3,2025-01-01,\t16:34,Amit Kumar Srivastava,Debit,50.0
4,2025-01-01,\t16:37,Amit Kumar Srivastava,Debit,120.0
...,...,...,...,...,...
1636,2026-01-29,\t21:43,Kanak Sweets,Debit,30.0
1637,This is an automatically generated statement. ...,NaN,nan,NaN,NaN
1638,Visit https://www.phonepe.com/terms-conditions...,NaN,nan,NaN,NaN
1639,Do not fall prey to fictitious offers of winni...,NaN,nan,NaN,NaN
1640,The contents of this email and document are co...,NaN,nan,NaN,NaN

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1641 entries, 0 to 1640
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1641 non-null   object
 1   Time                 1637 non-null   object
 2   Transaction Details  1641 non-null   object
 3   Transaction Type     1637 non-null   object
 4   Amount               1637 non-null   float64
dtypes: float64(1), object(4)
memory usage: 64.2+ KB

In [9]:
data = data.dropna(subset = ["Transaction Details","Transaction Type","Amount"]).copy()

In [10]:
data

            Date     Time     Transaction Details Transaction Type  Amount
0     2025-01-01  \t00:26         Siddharth Singh            Debit   500.0
1     2025-01-01  \t13:56           Sandeep Kumar            Debit   500.0
2     2025-01-01  \t14:32            CAFE CULTURE            Debit    15.0
3     2025-01-01  \t16:34   Amit Kumar Srivastava            Debit    50.0
4     2025-01-01  \t16:37   Amit Kumar Srivastava            Debit   120.0
...          ...      ...                     ...              ...     ...
1632  2026-01-29  \t13:22            Kanak Sweets            Debit    30.0
1633  2026-01-29  \t15:39                   EKART            Debit   325.0
1634  2026-01-29  \t16:42   CRISP ONLINE SERVICES            Debit   118.0
1635  2026-01-29  \t21:22            Kanak Sweets            Debit    20.0
1636  2026-01-29  \t21:43            Kanak Sweets            Debit    30.0

[1637 rows x 5 columns]

In [11]:
data["Time"] = data["Time"].astype(str).str.replace(r"\t" , "",regex = True )

In [12]:
data

            Date   Time     Transaction Details Transaction Type  Amount
0     2025-01-01  00:26         Siddharth Singh            Debit   500.0
1     2025-01-01  13:56           Sandeep Kumar            Debit   500.0
2     2025-01-01  14:32            CAFE CULTURE            Debit    15.0
3     2025-01-01  16:34   Amit Kumar Srivastava            Debit    50.0
4     2025-01-01  16:37   Amit Kumar Srivastava            Debit   120.0
...          ...    ...                     ...              ...     ...
1632  2026-01-29  13:22            Kanak Sweets            Debit    30.0
1633  2026-01-29  15:39                   EKART            Debit   325.0
1634  2026-01-29  16:42   CRISP ONLINE SERVICES            Debit   118.0
1635  2026-01-29  21:22            Kanak Sweets            Debit    20.0
1636  2026-01-29  21:43            Kanak Sweets            Debit    30.0

[1637 rows x 5 columns]

In [13]:
data=data.copy()
data['Date'] = pd.to_datetime(data['Date'])
data['Month'] = data['Date'].dt.month_name()
data['Day_Name'] = data['Date'].dt.day_name()
data['Is_Weekend'] = data['Date'].dt.dayofweek.isin([5, 6]).astype(int)

In [14]:
data

,Date,Time,Transaction Details,Transaction Type,Amount,Month,Day_Name,Is_Weekend
0,2025-01-01,00:26,Siddharth Singh,Debit,500.0,January,Wednesday,0
1,2025-01-01,13:56,Sandeep Kumar,Debit,500.0,January,Wednesday,0
2,2025-01-01,14:32,CAFE CULTURE,Debit,15.0,January,Wednesday,0
3,2025-01-01,16:34,Amit Kumar Srivastava,Debit,50.0,January,Wednesday,0
4,2025-01-01,16:37,Amit Kumar Srivastava,Debit,120.0,January,Wednesday,0
...,...,...,...,...,...,...,...,...
1632,2026-01-29,13:22,Kanak Sweets,Debit,30.0,January,Thursday,0
1633,2026-01-29,15:39,EKART,Debit,325.0,January,Thursday,0
1634,2026-01-29,16:42,CRISP ONLINE SERVICES,Debit,118.0,January,Thursday,0
1635,2026-01-29,21:22,Kanak Sweets,Debit,20.0,January,Thursday,0
1636,2026-01-29,21:43,Kanak Sweets,Debit,30.0,January,Thursday,0

In [15]:
data = data.drop("Date" , axis =1)

In [16]:
data

,Time,Transaction Details,Transaction Type,Amount,Month,Day_Name,Is_Weekend
0,00:26,Siddharth Singh,Debit,500.0,January,Wednesday,0
1,13:56,Sandeep Kumar,Debit,500.0,January,Wednesday,0
2,14:32,CAFE CULTURE,Debit,15.0,January,Wednesday,0
3,16:34,Amit Kumar Srivastava,Debit,50.0,January,Wednesday,0
4,16:37,Amit Kumar Srivastava,Debit,120.0,January,Wednesday,0
...,...,...,...,...,...,...,...
1632,13:22,Kanak Sweets,Debit,30.0,January,Thursday,0
1633,15:39,EKART,Debit,325.0,January,Thursday,0
1634,16:42,CRISP ONLINE SERVICES,Debit,118.0,January,Thursday,0
1635,21:22,Kanak Sweets,Debit,20.0,January,Thursday,0
1636,21:43,Kanak Sweets,Debit,30.0,January,Thursday,0

In [17]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

categories = ["Food and Dining",
    "Groceries and Daily Needs",
    "Shopping and E-commerce",
    "Travel and Transport",
    "Bills and Utilities",
    "Health and Medical",
    "Money Transfer and Investment",
    "Entertainment and Leisure",
    "Money Deposited or Received",
    "Education / Bills & Utilities",
    "Housing / Rent"
]

category_embeddings = model.encode(categories, convert_to_tensor=True)


def classify_transaction(text):
    if not isinstance(text, str) or text.strip() == "":
        return "Miscellaneous"
    

    text_embedding = model.encode(text, convert_to_tensor=True)
    
    cosine_scores = util.cos_sim(text_embedding, category_embeddings)

    best_match_idx = cosine_scores.argmax().item()
    return categories[best_match_idx]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [18]:

data['Category'] = data['Transaction Details'].apply(classify_transaction)

data[['Transaction Details', 'Amount', 'Category']].head(10)

      Transaction Details  Amount                       Category
0         Siddharth Singh   500.0             Health and Medical
1           Sandeep Kumar   500.0  Money Transfer and Investment
2            CAFE CULTURE    15.0                Food and Dining
3   Amit Kumar Srivastava    50.0             Health and Medical
4   Amit Kumar Srivastava   120.0             Health and Medical
5              ******7433   300.0    Money Deposited or Received
6   Received from SANDEEP   500.0    Money Deposited or Received
7    Received from BERLIN   500.0    Money Deposited or Received
8                  satyam    10.0                Food and Dining
9            Nitish Kumar  1700.0             Health and Medical

In [20]:
import re
import spacy
import pandas as pd
from sentence_transformers import SentenceTransformer, util

# 1. Load SpaCy NLP Model and SentenceTransformer
nlp = spacy.load("en_core_web_sm")
model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Categories List
categories = ["Food and Dining",
    "Groceries and Daily Needs",
    "Shopping and E-commerce",
    "Travel and Transport",
    "Bills and Utilities",
    "Health and Medical",
    "Money Transfer and Investment",
    "Entertainment and Leisure",
    "Money Deposited or Received",
    "Education / Bills & Utilities",
    "Housing / Rent"
]

category_embeddings = model.encode(categories, convert_to_tensor=True)

# 3. Consolidated & Expanded Keyword Regex Patterns
EDUCATION_PATTERN = r'\b(vishwavidyalaya|college|education|iit|institute|university|school|proudyogiki)\b'
HOUSING_PATTERN = r'\b(hostel|pg|rent|boys hostel|girls hostel)\b'
FOOD_PATTERN = r'\b(swiggy|zomato|cafe|sweets|bakery|restaurant|dhaba|nasta|jalebi|misthan|burger|food|crave|kulfi|icecream|ice cream|canteen|caterar|caterers|restorent)\b'
GROCERY_PATTERN = r'\b(kirana|provision|vegetable|fruit|dairy|store|mart|supermarket)\b'
TRAVEL_PATTERN = r'\b(ixigo|irctc|uts|railway|railways|redbus|bus|metro|uber|ola|rapido)\b'
RECHARGE_PATTERN = r'\b(recharge|bill|mobile|dth|jio|airtel|\bvi\b|bsnl|electricity|gas|broadband|tata play|air fiber|fiber)\b'
SHOPPING_PATTERN = r'\b(ekart|amazon|flipkart|myntra)\b'
HEALTH_PATTERN = r'\b(pharmacy|medical|chemist|hospital|clinic|lab|pathology|diagnostics|apollo|pharmeasy|1mg|netmeds|doctor|dr|lenskart|healthcare|dental|physician|radiology|xray|mri|rehabilitation|therapy|wellness|nutrition|optical|ambulance)\b'

def Smart_Categorize_SpaCy(df):
    results = [None] * len(df)
    texts_to_embed = []
    embed_indices_map = []
    
    for idx, row in df.iterrows():
        text_str = str(row['Transaction Details']).strip()
        txn_type = str(row.get('Type', '')).upper()
        
        # Priority 1: Direct Inflow / Deposit Rules
        if re.search(r'Received from', text_str, re.IGNORECASE) or txn_type == 'CREDIT':
            results[idx] = "Money Deposited or Received"
            continue

        # Priority 2: Specific Merchant & Service Patterns
        if re.search(EDUCATION_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Education / Bills & Utilities"
            continue
        if re.search(HOUSING_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Housing / Rent"
            continue
        if re.search(FOOD_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Food and Dining"
            continue
        if re.search(GROCERY_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Groceries and Daily Needs"
            continue
        if re.search(TRAVEL_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Travel and Transport"
            continue
        if re.search(RECHARGE_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Bills and Utilities"
            continue
        if re.search(SHOPPING_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Shopping and E-commerce"
            continue
        if re.search(HEALTH_PATTERN, text_str, re.IGNORECASE):
            results[idx] = "Health and Medical"
            continue

        # Priority 3: Fallback Money Transfer / Banking Keyword Patterns
        if re.search(r'Paid to|Transfer|Bank Account|\*+|\b\d{10}\b', text_str, re.IGNORECASE):
            results[idx] = "Money Transfer and Investment"
            continue

        # Priority 4: SpaCy Person Name Detection
        doc = nlp(text_str)
        is_person = any(ent.label_ == "PERSON" for ent in doc.ents)
        if is_person:
            results[idx] = "Money Transfer and Investment"
            continue

        # Priority 5: Queue for Deep Learning Embedding Fallback
        texts_to_embed.append(text_str)
        embed_indices_map.append(idx)
            
    # Deep Learning Cosine Similarity Fallback
    if texts_to_embed:
        embeddings = model.encode(texts_to_embed, convert_to_tensor=True)
        scores = util.cos_sim(embeddings, category_embeddings)
        
        for i, original_idx in enumerate(embed_indices_map):
            max_score, best_idx = scores[i].max(dim=0)
            if max_score.item() < 0.35:
                results[original_idx] = "Money Transfer and Investment"
            else:
                results[original_idx] = categories[best_idx.item()]
                
    return results

# 4. Apply Categorization
data['Category'] = Smart_Categorize_SpaCy(data)

# 5. Check Output
data[['Transaction Details', 'Amount', 'Category']].head(60)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

                   Transaction Details  Amount                       Category
0                      Siddharth Singh   500.0  Money Transfer and Investment
1                        Sandeep Kumar   500.0  Money Transfer and Investment
2                         CAFE CULTURE    15.0                Food and Dining
3                Amit Kumar Srivastava    50.0  Money Transfer and Investment
4                Amit Kumar Srivastava   120.0  Money Transfer and Investment
5                           ******7433   300.0  Money Transfer and Investment
6                Received from SANDEEP   500.0    Money Deposited or Received
7                 Received from BERLIN   500.0    Money Deposited or Received
8                               satyam    10.0  Money Transfer and Investment
9                         Nitish Kumar  1700.0  Money Transfer and Investment
10                        Nitish Kumar    40.0  Money Transfer and Investment
11      Received from Priyanshu Sharma    75.0    Money Deposited or Received
12                    The cafe culture   595.0                Food and Dining
13      Received from Mr NITISH  KUMAR   150.0    Money Deposited or Received
14      Received from Priyanshu Sharma   435.0    Money Deposited or Received
15      Received from Mr NITISH  KUMAR   435.0    Money Deposited or Received
16                               ixigo  2163.0           Travel and Transport
17                              satyam    10.0  Money Transfer and Investment
18                          ******5842    10.0  Money Transfer and Investment
19               Jio Prepaid Recharges    19.0            Bills and Utilities
20     LOKESH JOSHI S O INDARLAL JOSHI    33.0  Money Transfer and Investment
21                        Kanak Sweets    30.0                Food and Dining
22                        Kanak Sweets    30.0                Food and Dining
23            Received from ******4123   435.0    Money Deposited or Received
24                        ASHA MEDICAL   180.0             Health and Medical
25               Amit Kumar Srivastava   100.0  Money Transfer and Investment
26                     Siddharth Singh    50.0  Money Transfer and Investment
27                          ******7433  3960.0  Money Transfer and Investment
28                     Siddharth Singh    10.0  Money Transfer and Investment
29                        Nitish Kumar   176.0  Money Transfer and Investment
30  Received from Avinash kumar Tiwari  2700.0    Money Deposited or Received
31                    Amit Kumar Singh  1000.0  Money Transfer and Investment
32                    VIVEK KUMAR JAIN    74.0  Money Transfer and Investment
33                         GG IES ICOT    30.0  Money Transfer and Investment
34                         GG IES ICOT    40.0  Money Transfer and Investment
35                    Priyanshu Sharma    25.0  Money Transfer and Investment
36     LOKESH JOSHI S O INDARLAL JOSHI    40.0  Money Transfer and Investment
37                    Priyanshu Sharma    40.0  Money Transfer and Investment
38                          ******4123    70.0  Money Transfer and Investment
39                    Ankit Kumar Ojha   700.0  Money Transfer and Investment
40                    VIVEK KUMAR JAIN     6.0  Money Transfer and Investment
41                    VIVEK KUMAR JAIN    20.0  Money Transfer and Investment
42                          ******4935    40.0  Money Transfer and Investment
43                      BIKANER SWEETS    50.0                Food and Dining
44      Received from Priyanshu Sharma    25.0    Money Deposited or Received
45               Amit Kumar Srivastava    50.0  Money Transfer and Investment
46     LOKESH JOSHI S O INDARLAL JOSHI   133.0  Money Transfer and Investment
47       Received from Siddharth Singh   180.0    Money Deposited or Received
48                              satyam    10.0  Money Transfer and Investment
49                    Priyanshu Sharma    24.0  Money Transfer and Investment
50                              satyam    10.0  Money Transfer and Investment
51            Shree Balaji Super Bazar   268.0  Money Transfer and Investment
52            Received from ******4123   110.0    Money Deposited or Received
53                              BERLIN  2000.0  Money Transfer and Investment
54                       WWW AIRTEL IN   349.0            Bills and Utilities
55                    VIVEK KUMAR JAIN    30.0  Money Transfer and Investment
56                        KANAK SWEETS    40.0                Food and Dining
57               Amit Kumar Srivastava     5.0  Money Transfer and Investment
58                              satyam    10.0  Money Transfer and Investment
59         Received from Deepak bharti  7750.0    Money Deposited or Received

In [32]:
x = data["Transaction Details"].fillna("").astype(str).str.lower().str.strip()
y = data["Category"]

In [33]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size = 0.2, random_state = 42 , stratify = y )

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(ngram_range =(1,2 ),max_features =5000)
x_train_vec = tfidf.fit_transform(x_train)
x_test_vec = tfidf.transform(x_test)

In [35]:
from sklearn.linear_model import LogisticRegression
import joblib
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(x_train_vec, y_train)
accuracy = model.score(x_test_vec, y_test)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 98.78%

In [36]:
import joblib
joblib.dump(model, 'transaction_classifier.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']

In [37]:
import pandas as pd

# Load ground truth or categorized dataframe
data = pd.read_csv('save.csv')

# --- PHASE 3: ANALYTICS ENGINE FUNCTIONS ---

def generate_financial_analytics(df):
    print("="*50)
    print("        AUTOMATED FINANCIAL ANALYTICS REPORT        ")
    print("="*50 + "\n")
    
    # 1. Category-wise Total Expense Breakdown
    print("1. CATEGORY-WISE SPENDING SUMMARY:")
    category_summary = df.groupby('Category')['Amount'].agg(['sum', 'count']).reset_index()
    category_summary.columns = ['Category', 'Total Amount (₹)', 'Transaction Count']
    category_summary['Percentage (%)'] = (category_summary['Total Amount (₹)'] / category_summary['Total Amount (₹)'].sum()) * 100
    category_summary = category_summary.sort_values(by='Total Amount (₹)', ascending=False)
    print(category_summary.to_string(index=False))
    print("\n" + "-"*50 + "\n")
    
    # 2. Monthly Trend Analysis (if 'Month' column exists)
    if 'Month' in df.columns:
        print("2. MONTHLY SPENDING TRENDS:")
        monthly_summary = df.groupby('Month')['Amount'].sum().reset_index()
        monthly_summary.columns = ['Month', 'Total Spent (₹)']
        print(monthly_summary.to_string(index=False))
        print("\n" + "-"*50 + "\n")
        
    # 3. Top 5 Merchants/Receivers
    print("3. TOP 5 MOST FREQUENT MERCHANTS/PAYEES:")
    top_merchants = df['Transaction Details'].value_counts().head(5).reset_index()
    top_merchants.columns = ['Merchant / Payee Details', 'Frequency']
    print(top_merchants.to_string(index=False))
    print("\n" + "="*50)

# Run Analytics Engine
generate_financial_analytics(data)

==================================================
        AUTOMATED FINANCIAL ANALYTICS REPORT
==================================================

1. CATEGORY-WISE SPENDING SUMMARY:
                     Category  Total Amount (₹)  Transaction Count  Percentage (%)
Money Transfer and Investment         848662.38               1004       58.631539
  Money Deposited or Received         511003.50                311       35.303699
               Housing / Rent          21500.00                  4        1.485371
Education / Bills & Utilities          15284.50                  9        1.055960
              Food and Dining          13712.64                178        0.947365
          Bills and Utilities          12558.57                 31        0.867634
      Shopping and E-commerce          12334.00                 22        0.852119
         Travel and Transport           6516.70                  7        0.450219
    Groceries and Daily Needs           4529.00                 66        0.312895
           Health and Medical           1349.00                  5        0.093198

--------------------------------------------------

2. MONTHLY SPENDING TRENDS:
    Month  Total Spent (₹)
    April         48737.64
   August         69920.82
 December        107256.82
 February         34554.54
  January        218522.82
     July         81676.15
     June        172277.22
    March         58156.62
      May        175125.82
 November        258140.52
  October         84514.32
September        138567.00

--------------------------------------------------

3. TOP 5 MOST FREQUENT MERCHANTS/PAYEES:
        Merchant / Payee Details  Frequency
 LOKESH JOSHI S O INDARLAL JOSHI        103
        Received from ******4123         98
                      ******4123         77
                    Kanak Sweets         64
  Received from Priyanshu Sharma         56

==================================================